services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pawfect-planner-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - db
    networks:
      - app_network

  gemini-service:
    build:
      context: ./backend/gemini-service
      dockerfile: Dockerfile
    container_name: gemini-service
    ports:
      - "5000:5000"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./backend/gemini-service:/app
    networks:
      - app_network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DB4PawfectPlanner
      POSTGRES_DB: pets_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:
  data:

networks:
  app_network:
    driver: bridge