services:
  db:
    image: postgres:15
    container_name: pawfect-planner-db
    restart: always
    env_file:
      - .env  # ✅ Loads environment variables from .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pawfect-planner-backend
    env_file:
      - .env  # ✅ Ensures DATABASE_URL and DOG_API_KEY load correctly
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - app_network

  gemini-service:
    build:
      context: ./backend
      dockerfile: gemini-service/Dockerfile
    container_name: gemini-service
    env_file:
      - .env  # ✅ Ensures GEMINI_API_KEY loads correctly
    ports:
      - "5000:5000"
    volumes:
      - ./backend/gemini-service:/app
    depends_on:
      - backend
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pawfect-planner-frontend
    ports:
      - "3000:80"  # ✅ Corrects mapping (3000 -> 80 for Nginx)
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge