services:
  db:
    image: postgres:15
    container_name: pawfect-planner-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pawfect-planner-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DOG_API_KEY: ${DOG_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - app_network

  gemini-service:
    build:
      context: ./backend  # No need to install dependencies again
      dockerfile: gemini-service/Dockerfile
    container_name: gemini-service
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./backend/gemini-service:/app
    depends_on:
      - backend
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pawfect-planner-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge